# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/

dist: xenial
language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$HOME/gopath/pkg/mod"
before_install:
- openssl aes-256-cbc -K $encrypted_e5acc89010f1_key -iv $encrypted_e5acc89010f1_iv -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# install - install any dependencies required
install:
- go get github.com/gohugoio/hugo@v0.62.0
before_script:
- mkdir -p public_github 2> /dev/null
- mkdir -p public_gitee 2> /dev/null
# script - run the build script
script:
- hugo --baseURL https://jeremyxu2010.github.io/ -d public_github
- hugo --baseURL https://jeremy-xu.oschina.io/ -d public_gitee
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN" # Set in travis-ci.org dashboard, marked secure
  email: "$GITHUB_EMAIL" # Set in travis-ci.org dashboard, marked secure
  name: "$GITHUB_USERNAME" # Set in travis-ci.org dashboard, marked secure
  repo: "$GITHUB_USERNAME/$GITHUB_USERNAME.github.io"
  target_branch: master
  verbose: true
  keep-history: false
  local-dir: public_github
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: bash .travis/deploy_to_gitee.sh
  on:
    branch: master
addons:
  ssh_known_hosts:
  - github.com
  - gitee.com
